# This build will run every Friday at 9:30 AM UTC (5:30 PM MYT),
# will create a new release tag if the current date is a cutoff date.
name: Bi-weekly cutoff build
on:
  workflow_dispatch:

jobs:
    build-if-cutoff:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Check if today is a cutoff date
              id: cutoff
              run: |
                  chmod +x ./scripts/check-cutoff.sh
                  ./scripts/check-cutoff.sh

            - name: Trigger Ad-hoc Release Tag Workflow
              if: steps.cutoff.outputs.should_cutoff == 'true'
              run: |
                  gh workflow run build-release-tag.yaml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
