name: Release

on:
  schedule:
    - cron: '0 17 * * 5'  # Every Friday at 5PM UTC
  workflow_dispatch:
    inputs:
      stable:
        description: 'Is this a stable release?'
        required: false
        default: 'false'  # default to RC if not specified

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm clean-install

      - name: Audit installed packages
        run: npm audit signatures

      - name: Set STABLE_RELEASE environment variable
        run: echo "STABLE_RELEASE=${{ github.event.inputs.stable || 'false' }}" >> $GITHUB_ENV

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
